### ISSUE TITLE
贵公司的支付api，宇宙最烂

### ISSUE THREAD

**Issue by irocn** [wechatpay-apiv3/CertificateDownloader#17]
贵公司的支付api，宇宙最烂！！！

**Comment by Eric-Lee-Handyman** [comment]
您好，感谢反馈。
请问具体是哪个API？
烂的地方具体是指哪些？
麻烦细化下，我们可以跟业务反馈。

**Comment by allen1995** [comment]
1.2.0版本和1.1.0下载平台证书失败。
已检查商户号、商户证书密钥、商户证书序列号，未发现问题。
![企业微信截图_16570114045408_LI](https://user-images.githubusercontent.com/23219034/177291489-39e9d490-3fcf-4c9d-9411-3d9ab642c0e4.jpg)

**Comment by wowdw** [comment]
草 是一种植物!

**Comment by JanmasCromwell** [comment]
复议

**Comment by chenyu1990** [comment]
> 您好，感谢反馈。 请问具体是哪个API？ 烂的地方具体是指哪些？ 麻烦细化下，我们可以跟业务反馈。

首先中文描述与官方文档不统一，其次，本仓库示例不指向你们自己的其它工具的结果文件名称，导致使用成本增加。就这一点你们就够垃圾了。

**Comment by ryzencool** [comment]
复议

**Comment by huimingz** [comment]
复议，真不明白是哪个天才产品或者架构师想出来的这个解决方案，根本不把对接方当人看
