### ISSUE TITLE
找不到证书序列号对应的证书

### ISSUE THREAD

**Issue by charliex2** [wechatpay-apiv3/CertificateDownloader#19]
该 jar 工具，我按文档示例，带上 `-c` 参数，则会报错 
```
[main] ERROR com.wechat.pay.contrib.apache.httpclient.auth.CertificatesVerifier - 找不到证书序列号对应的证书，序列号：...
```
不带该参数即可正常，原因不明没有深究。

供各位坑友参考

**Comment by xy-peng** [comment]
`-c` 是当你本地已经有微信支付平台证书的情况下，可以用它来验证下载的证书的真实性。

通常大家都没有证书，不然也不会下载嘛。我调整下文档，说明下情况。

**Comment by xy-peng** [comment]
@charliex2 文档已更新，你可以看看是否说明清楚了。

**Comment by charliex2** [comment]
我已经明白，感谢您的快速回复。
