### ISSUE TITLE
平台证书安全性校验

### ISSUE THREAD

**Issue by baizhimafa** [wechatpay-apiv3/CertificateDownloader#2]
![1583135729461](https://user-images.githubusercontent.com/20203278/75657841-09f91e80-5ca2-11ea-82aa-dadc4feafb38.jpg)

平台证书安全性校验这里的这一步是否是多余的，如若证书被中间人劫持替换了，中间人自签证书的颁发者也可以是`Tenpay.com Root CA`

**Comment by xy-peng** [comment]
@baizhimafa 第3/4步应当结合起来使用。

顺序上反过来可能更清晰一些，先通过信任链验证证书的有效性，再核对证书的颁发者。
