### ISSUE TITLE
首次下载的问题：平台证书路径-c 指令忽略了没有传 会报错误无法下载

### ISSUE THREAD

**Issue by aoaoms** [wechatpay-apiv3/CertificateDownloader#3]
报错：java.io.FileNotFoundException

代码位置：class CertificateDownloader 84 行

代码：
// 这里判断 wechatpayCertificatePath 改成空字符判断 可正常下载
if (wechatpayCertificatePath ==“”) {
            //不做验签
            builder.withValidator(response -> true);
} else {
            List<X509Certificate> certs = new ArrayList<>();

            certs.add(PemUtil.loadCertificate(new FileInputStream(wechatpayCertificatePath)));
            builder.withWechatpay(certs);
 }

请参阅

**Comment by xy-peng** [comment]
谢谢反馈。

我们希望使用者传本地的平台证书进行签名验证，加强整个过程的安全性。所以，用户忽略了没有传或者漏传的情况，报错是更合理的。如果没有本地的平台证书，不使用-c来传参就好了。
