### ISSUE TITLE
File not available

### ISSUE THREAD

**Issue by wenjies** [wechatpay-apiv3/CertificateDownloader#9]
java -jar CertificateDownloader.jar -h
Error: Unable to access jarfile CertificateDownloader.jar

**Comment by xy-peng** [comment]
把jar文件下载到本地了吗？

**Comment by Lov3ling** [comment]
Error: Unable to access jarfile CertificateDownloader.jar

**Comment by xy-peng** [comment]
> Error: Unable to access jarfile CertificateDownloader.jar

jar包下载到本地当前目录了吗？
